# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fl_grpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fl_grpc.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rfl_grpc.proto\".\n\x0fsignSGD_Request\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0f\n\x07sgn_ori\x18\x02 \x03(\x05\"#\n\x10signSGD_Response\x12\x0f\n\x07sgn_upd\x18\x01 \x03(\x02\"0\n\x11IdxRequest_uint32\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0f\n\x07idx_ori\x18\x02 \x03(\r\"%\n\x12IdxResponse_uint32\x12\x0f\n\x07idx_upd\x18\x01 \x03(\r\"1\n\x11GradRequest_int32\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08grad_ori\x18\x02 \x03(\x05\"&\n\x12GradResponse_int32\x12\x10\n\x08grad_upd\x18\x01 \x03(\x05\"1\n\x11GradRequest_float\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08grad_ori\x18\x02 \x03(\x02\"&\n\x12GradResponse_float\x12\x10\n\x08grad_upd\x18\x01 \x03(\x02\"1\n\x11\x44\x61taRequest_int32\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08\x64\x61ta_ori\x18\x02 \x03(\x05\"&\n\x12\x44\x61taResponse_int32\x12\x10\n\x08\x64\x61ta_upd\x18\x01 \x03(\x05\x32\xbd\x02\n\x07\x46L_Grpc\x12=\n\x10UpdateIdx_uint32\x12\x12.IdxRequest_uint32\x1a\x13.IdxResponse_uint32\"\x00\x12=\n\x10UpdateGrad_int32\x12\x12.GradRequest_int32\x1a\x13.GradResponse_int32\"\x00\x12=\n\x10UpdateGrad_float\x12\x12.GradRequest_float\x1a\x13.GradResponse_float\"\x00\x12<\n\x0f\x44\x61taTrans_int32\x12\x12.DataRequest_int32\x1a\x13.DataResponse_int32\"\x00\x12\x37\n\x0eUpdate_SignSGD\x12\x10.signSGD_Request\x1a\x11.signSGD_Response\"\x00\x62\x06proto3')
)




_SIGNSGD_REQUEST = _descriptor.Descriptor(
  name='signSGD_Request',
  full_name='signSGD_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='signSGD_Request.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sgn_ori', full_name='signSGD_Request.sgn_ori', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=63,
)


_SIGNSGD_RESPONSE = _descriptor.Descriptor(
  name='signSGD_Response',
  full_name='signSGD_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sgn_upd', full_name='signSGD_Response.sgn_upd', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=100,
)


_IDXREQUEST_UINT32 = _descriptor.Descriptor(
  name='IdxRequest_uint32',
  full_name='IdxRequest_uint32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='IdxRequest_uint32.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='idx_ori', full_name='IdxRequest_uint32.idx_ori', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=150,
)


_IDXRESPONSE_UINT32 = _descriptor.Descriptor(
  name='IdxResponse_uint32',
  full_name='IdxResponse_uint32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idx_upd', full_name='IdxResponse_uint32.idx_upd', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=189,
)


_GRADREQUEST_INT32 = _descriptor.Descriptor(
  name='GradRequest_int32',
  full_name='GradRequest_int32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GradRequest_int32.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grad_ori', full_name='GradRequest_int32.grad_ori', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=240,
)


_GRADRESPONSE_INT32 = _descriptor.Descriptor(
  name='GradResponse_int32',
  full_name='GradResponse_int32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='grad_upd', full_name='GradResponse_int32.grad_upd', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=280,
)


_GRADREQUEST_FLOAT = _descriptor.Descriptor(
  name='GradRequest_float',
  full_name='GradRequest_float',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GradRequest_float.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grad_ori', full_name='GradRequest_float.grad_ori', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=331,
)


_GRADRESPONSE_FLOAT = _descriptor.Descriptor(
  name='GradResponse_float',
  full_name='GradResponse_float',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='grad_upd', full_name='GradResponse_float.grad_upd', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=371,
)


_DATAREQUEST_INT32 = _descriptor.Descriptor(
  name='DataRequest_int32',
  full_name='DataRequest_int32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DataRequest_int32.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_ori', full_name='DataRequest_int32.data_ori', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=422,
)


_DATARESPONSE_INT32 = _descriptor.Descriptor(
  name='DataResponse_int32',
  full_name='DataResponse_int32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_upd', full_name='DataResponse_int32.data_upd', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=462,
)

DESCRIPTOR.message_types_by_name['signSGD_Request'] = _SIGNSGD_REQUEST
DESCRIPTOR.message_types_by_name['signSGD_Response'] = _SIGNSGD_RESPONSE
DESCRIPTOR.message_types_by_name['IdxRequest_uint32'] = _IDXREQUEST_UINT32
DESCRIPTOR.message_types_by_name['IdxResponse_uint32'] = _IDXRESPONSE_UINT32
DESCRIPTOR.message_types_by_name['GradRequest_int32'] = _GRADREQUEST_INT32
DESCRIPTOR.message_types_by_name['GradResponse_int32'] = _GRADRESPONSE_INT32
DESCRIPTOR.message_types_by_name['GradRequest_float'] = _GRADREQUEST_FLOAT
DESCRIPTOR.message_types_by_name['GradResponse_float'] = _GRADRESPONSE_FLOAT
DESCRIPTOR.message_types_by_name['DataRequest_int32'] = _DATAREQUEST_INT32
DESCRIPTOR.message_types_by_name['DataResponse_int32'] = _DATARESPONSE_INT32
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

signSGD_Request = _reflection.GeneratedProtocolMessageType('signSGD_Request', (_message.Message,), dict(
  DESCRIPTOR = _SIGNSGD_REQUEST,
  __module__ = 'fl_grpc_pb2'
  # @@protoc_insertion_point(class_scope:signSGD_Request)
  ))
_sym_db.RegisterMessage(signSGD_Request)

signSGD_Response = _reflection.GeneratedProtocolMessageType('signSGD_Response', (_message.Message,), dict(
  DESCRIPTOR = _SIGNSGD_RESPONSE,
  __module__ = 'fl_grpc_pb2'
  # @@protoc_insertion_point(class_scope:signSGD_Response)
  ))
_sym_db.RegisterMessage(signSGD_Response)

IdxRequest_uint32 = _reflection.GeneratedProtocolMessageType('IdxRequest_uint32', (_message.Message,), dict(
  DESCRIPTOR = _IDXREQUEST_UINT32,
  __module__ = 'fl_grpc_pb2'
  # @@protoc_insertion_point(class_scope:IdxRequest_uint32)
  ))
_sym_db.RegisterMessage(IdxRequest_uint32)

IdxResponse_uint32 = _reflection.GeneratedProtocolMessageType('IdxResponse_uint32', (_message.Message,), dict(
  DESCRIPTOR = _IDXRESPONSE_UINT32,
  __module__ = 'fl_grpc_pb2'
  # @@protoc_insertion_point(class_scope:IdxResponse_uint32)
  ))
_sym_db.RegisterMessage(IdxResponse_uint32)

GradRequest_int32 = _reflection.GeneratedProtocolMessageType('GradRequest_int32', (_message.Message,), dict(
  DESCRIPTOR = _GRADREQUEST_INT32,
  __module__ = 'fl_grpc_pb2'
  # @@protoc_insertion_point(class_scope:GradRequest_int32)
  ))
_sym_db.RegisterMessage(GradRequest_int32)

GradResponse_int32 = _reflection.GeneratedProtocolMessageType('GradResponse_int32', (_message.Message,), dict(
  DESCRIPTOR = _GRADRESPONSE_INT32,
  __module__ = 'fl_grpc_pb2'
  # @@protoc_insertion_point(class_scope:GradResponse_int32)
  ))
_sym_db.RegisterMessage(GradResponse_int32)

GradRequest_float = _reflection.GeneratedProtocolMessageType('GradRequest_float', (_message.Message,), dict(
  DESCRIPTOR = _GRADREQUEST_FLOAT,
  __module__ = 'fl_grpc_pb2'
  # @@protoc_insertion_point(class_scope:GradRequest_float)
  ))
_sym_db.RegisterMessage(GradRequest_float)

GradResponse_float = _reflection.GeneratedProtocolMessageType('GradResponse_float', (_message.Message,), dict(
  DESCRIPTOR = _GRADRESPONSE_FLOAT,
  __module__ = 'fl_grpc_pb2'
  # @@protoc_insertion_point(class_scope:GradResponse_float)
  ))
_sym_db.RegisterMessage(GradResponse_float)

DataRequest_int32 = _reflection.GeneratedProtocolMessageType('DataRequest_int32', (_message.Message,), dict(
  DESCRIPTOR = _DATAREQUEST_INT32,
  __module__ = 'fl_grpc_pb2'
  # @@protoc_insertion_point(class_scope:DataRequest_int32)
  ))
_sym_db.RegisterMessage(DataRequest_int32)

DataResponse_int32 = _reflection.GeneratedProtocolMessageType('DataResponse_int32', (_message.Message,), dict(
  DESCRIPTOR = _DATARESPONSE_INT32,
  __module__ = 'fl_grpc_pb2'
  # @@protoc_insertion_point(class_scope:DataResponse_int32)
  ))
_sym_db.RegisterMessage(DataResponse_int32)



_FL_GRPC = _descriptor.ServiceDescriptor(
  name='FL_Grpc',
  full_name='FL_Grpc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=465,
  serialized_end=782,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateIdx_uint32',
    full_name='FL_Grpc.UpdateIdx_uint32',
    index=0,
    containing_service=None,
    input_type=_IDXREQUEST_UINT32,
    output_type=_IDXRESPONSE_UINT32,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateGrad_int32',
    full_name='FL_Grpc.UpdateGrad_int32',
    index=1,
    containing_service=None,
    input_type=_GRADREQUEST_INT32,
    output_type=_GRADRESPONSE_INT32,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateGrad_float',
    full_name='FL_Grpc.UpdateGrad_float',
    index=2,
    containing_service=None,
    input_type=_GRADREQUEST_FLOAT,
    output_type=_GRADRESPONSE_FLOAT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DataTrans_int32',
    full_name='FL_Grpc.DataTrans_int32',
    index=3,
    containing_service=None,
    input_type=_DATAREQUEST_INT32,
    output_type=_DATARESPONSE_INT32,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Update_SignSGD',
    full_name='FL_Grpc.Update_SignSGD',
    index=4,
    containing_service=None,
    input_type=_SIGNSGD_REQUEST,
    output_type=_SIGNSGD_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FL_GRPC)

DESCRIPTOR.services_by_name['FL_Grpc'] = _FL_GRPC

# @@protoc_insertion_point(module_scope)
